name: DreamWeaver Autolearn Scan

on:
  push:
    paths:
      - 'domains/**.md'
      - 'scripts/**.py'
      - 'domain-truths.md'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Domain Truth Scanner
        run: python scripts/scan_domain_truths.py
